### ISSUE TITLE
Incorrect information in the flatbuffers/LA README.md

### ISSUE THREAD

**Issue by emannotava** [rh-hideout/rhh-docs#2]
" TRSPB - Animation Spring Bone" this is listed with a checkmark, suggesting that there is a flatbuffer for it, however there is no trspb.fbs flatbuffer within the LA/Animation folder nor in any other folder.

Additionally there's also no mention of the trac**r** format, not even under the unk section

**Comment by mvit** [comment]
TRSPB is in the model folder, thought it belonged there with tralk and the other rig-based physics properties.
TRACR has been added to the README.
